services:
  - type: web
    name: sa-portfolio
    env: docker
    region: frankfurt
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 465
      - key: MAIL_USERNAME
        value: aleksstanov84@gmail.com
      - key: MAIL_PASSWORD
        value: your_smtp_password
      - key: MAIL_ENCRYPTION
        value: ssl
      - key: MAIL_FROM_ADDRESS
        value: aleksstanov84@gmail.com
      - key: MAIL_FROM_NAME
        value: SA-Portfolio
