services:
  - type: web
    name: sa-portfolio
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d4njetogjchc73f798vg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: sa_portfolio_db_indk
      - key: DB_USERNAME
        value: sa_portfolio_db_indk_user
      - key: DB_PASSWORD
        value: j2fnUIINJy7Tbwzw9zeHsJuaEz5oGedz
      - key: APP_URL
        value: https://sa-portfolio.onrender.com

databases:
  - name: sa-portfolio-db
    plan: free
